[workspace]
resolver = "3"
members = [
    "action-processor", "cognitive-load-processor",
    "plotly-processor",
    "web",
]

# Optional: specify a default package to build
 default-members = ["web"]
