[package]
name = "mteam-dashboard-cognitive-load-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.137"
chrono = "0.4.39"
mteam-dashboard-action-processor = { path = "../action-processor" }